In [1]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve
import pandas as pd

### Problem #1

P1175; P1200; P1250; P1350; C1350; C1375; C1450; C1550; C1600

In [2]:
S_t0 = np.array([46.60, 51.55, 63.30, 95.30, 99.55, 84.90, 47.25, 15.80, 7.9])
securities_puts = np.array([1175, 1200, 1250, 1350, 0, 0, 0, 0, 0])
securities_calls = np.array([0, 0, 0, 0, 1350, 1375, 1450, 1550, 1600])                 

In [3]:
first_state_choice = [800,950,1100]
last_state_choice = [1650,1700,1800]

In [4]:
base_states = [1187.5, 1225, 1300, 1362.5, 1412.5, 1500, 1575]

In [5]:
market_models = [[i] + base_states + [j] for i in first_state_choice for j in last_state_choice]
market_models = np.array(market_models).T

In [6]:
def payoff(strike: float, stock: float, o_type: str):
    
    if o_type == "Call":
        if strike <= 0:
            return 0
        else:
            return max((stock - strike), 0)
    elif o_type == "Put":
        return max(strike - stock, 0)
    else:
        print("Enter either o_type = 'Call' or 'Put'")

Example Code

```python
put_lst=[]
for k in range(0,9):
    put_lst.append([payoff(securities_puts[i], 
       market_models[:,0][k], 
       "Put") for i in range(len(securities_puts))])


```python
call_lst=[]

for k in range(0,9):
    call_lst.append([payoff(securities_calls[i], 
       market_models[:,0][k], 
       "Call") for i in range(len(securities_puts))]) 
    

```python
M1 =np.array(put_lst).T + np.array(call_lst).T
print(M1)



### Get all Matrix

In [7]:
def get_matrix(n):
    
    put_lst=[]

    for k in range(0,9):
        put_lst.append([payoff(securities_puts[i], 
           market_models[:,n][k], 
           "Put") for i in range(len(securities_puts))])  
        
    call_lst=[]

    for k in range(0,9):
        call_lst.append([payoff(securities_calls[i], 
           market_models[:,n][k], 
           "Call") for i in range(len(securities_puts))]) 
        
    M =np.array(put_lst).T + np.array(call_lst).T
    return M

In [8]:
M0 = get_matrix(0)
M1 = get_matrix(1)
M2 = get_matrix(2)
M3 = get_matrix(3)
M4 = get_matrix(4)
M5 = get_matrix(5)
M6 = get_matrix(6)
M7 = get_matrix(7)
M8 = get_matrix(8)

Text Book problem (Page 100-103)

In [9]:
A = np.array([[200,0,0],
        [300,50,0,],
         [400,150,50]])

B = np.array([[25,100,175,300],
             [0,50,125,250],
             [0,0,25,150],
             [0,0,0,100]])

a1 = np.array([51.55,77.70,116.55])
b1 = np.array([71.10, 47.25, 15.80, 7.90])

print(np.linalg.solve(A,a1))
print(np.linalg.solve(B,b1))

[0.25775 0.0075  0.2465 ]
[0.17  0.155 0.158 0.079]


In [10]:
def get_Q(M, b_array, n):
    
    
    A = M[:n, :n]
    b = b_array[:n]
    
    q0 = np.linalg.solve(A,b)
    
    A1 = M[n:, n:]
    b1 = b_array[n:]
    
    q1 = np.linalg.solve(A1,b1)
    
    q = np.concatenate((q0,q1))
    
    return q, A, A1, M

### Test get_Q func on the Text Book problem (Page 100-103)

Testing on the TB Example

In [11]:
M_tb = np.array([[200,0,0,0,0,0,0],
                [300,50,0,0,0,0,0],
                [400,150,50,0,0,0,0],
                [0,0,0,25,100,175,300],
                [0,0,0,0,50,125,250],
                [0,0,0,0,0,25,150],
                [0,0,0,0,0,0,100]])

b_tb = np.array([51.55,77.70, 116.55,71.10,47.25,15.80,7.90])
q_tb = get_Q(M_tb, b_tb, 3)[0]
print(q_tb)

[0.25775 0.0075  0.2465  0.17    0.155   0.158   0.079  ]


In [12]:
all_Q = [get_Q(i, S_t0, 4)[0] for i in [M0, M1, M2, M3, M4, M5, M6, M7, M8]]

In [13]:
M0

array([[375. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [450. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [550. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 300. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 275. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 200. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 100. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. ]])

In [14]:
M1

array([[375. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [450. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [550. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 350. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 325. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 250. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 150. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 100. ]])

In [15]:
M2

array([[375. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [450. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [550. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 450. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 425. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 350. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 250. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 200. ]])

In [16]:
M3

array([[225. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [250. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [300. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 300. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 275. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 200. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 100. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. ]])

In [17]:
M4

array([[225. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [250. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [300. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 350. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 325. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 250. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 150. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 100. ]])

In [18]:
M5

array([[225. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [250. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [300. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 450. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 425. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 350. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 250. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 200. ]])

In [19]:
M6

array([[ 75. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [100. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [150. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [250. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 300. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 275. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 200. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 100. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. ]])

In [20]:
M7

array([[ 75. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [100. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [150. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [250. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 350. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 325. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 250. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 150. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 100. ]])

In [21]:
M8

array([[ 75. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [100. ,  12.5,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [150. ,  62.5,  25. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [250. , 162.5, 125. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  12.5,  62.5, 150. , 225. , 450. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 125. , 200. , 425. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  50. , 125. , 350. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  25. , 250. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 200. ]])

In [22]:
pd.DataFrame(all_Q)

0         1         2         3      4      5      6             7  \
0  0.124267  0.147467 -0.073467  0.243467  0.106  0.062  0.313  2.220446e-17   
1  0.124267  0.147467 -0.073467  0.243467 -0.052  0.220  0.155  1.580000e-01   
2  0.124267  0.147467 -0.073467  0.243467 -0.131  0.299  0.076  2.370000e-01   
3  0.207111 -0.018222  0.092222  0.077778  0.106  0.062  0.313  2.220446e-17   
4  0.207111 -0.018222  0.092222  0.077778 -0.052  0.220  0.155  1.580000e-01   
5  0.207111 -0.018222  0.092222  0.077778 -0.131  0.299  0.076  2.370000e-01   
6  0.621333 -0.846667  0.920667 -0.750667  0.106  0.062  0.313  2.220446e-17   
7  0.621333 -0.846667  0.920667 -0.750667 -0.052  0.220  0.155  1.580000e-01   
8  0.621333 -0.846667  0.920667 -0.750667 -0.131  0.299  0.076  2.370000e-01   

        8  
0  0.1580  
1  0.0790  
2  0.0395  
3  0.1580  
4  0.0790  
5  0.0395  
6  0.1580  
7  0.0790  
8  0.0395

Since not all of the above Q vectors are non-positive (in other word, we have some negative values). The model is **not** arbitrage free.

Since this is not arbitrage free model, I did not calculate the RMSE.