In [1]:
import pandas as pd
import numpy as np

In [2]:
call_strikes = np.array([1175,1200,1225,1250,1275,1300,1325,1350,1375,1400,1425,1450,1475])
call_mkt_px = np.array([67.1,46.5,41,28.5,22.8,15.8,9.5,6.8,4.1,2.5,1.4,0.9,0.5])
call_bid_px = np.array([68,52.8,40.3,29.6,21.3,15,10,6.3,4,2.5,1.4,0.8,0.35])
call_ask_px = np.array([70,54.8,42.3,31.6,23.3,16.2,11,7.3,4.7,3.2,1.85,1.25,0.8])

call_df = pd.DataFrame({"strikes":call_strikes,
                       "mkt_px":call_mkt_px,
                       "bid":call_bid_px,
                       "ask":call_ask_px})

call_df['mid'] = (call_df['ask'] + call_df['bid'])/2

call_df["relative_err"] = abs(call_df['mkt_px'] - call_df['mid']) / call_df['mid']
avg_abs_err_call = call_df['relative_err'].sum() / call_df.shape[0]


put_strikes = np.array([800,900,950,995,1025,1050,1060,1075,1100,1150,1175,1200])
put_mkt_px = np.array([1.65,4.3,5.4,10.1,13,13.6,16.5,22.5,26,39,44,53])
put_bid_px = np.array([1.2,3.4,5.3,8.5,11.1,14,15.7,18,22.7,35.3,44.1,53.9])
put_ask_px = np.array([1.65,4.1,6.3,9.5,12.6,15.5,17.2,19.5,24.7,37.3,46.1,55.9])

put_df = pd.DataFrame({"strikes":put_strikes,
                       "mkt_px":put_mkt_px,
                       "bid":put_bid_px,
                       "ask":put_ask_px})

put_df['mid'] = (put_df['ask'] + put_df['bid'])/2

put_df["relative_err"] = abs(put_df['mkt_px'] - put_df['mid']) / put_df['mid']
avg_abs_err_put = put_df['relative_err'].sum() / put_df.shape[0]

### Relative Error

In [3]:
call_df

strikes  mkt_px    bid    ask     mid  relative_err
0      1175    67.1  68.00  70.00  69.000      0.027536
1      1200    46.5  52.80  54.80  53.800      0.135688
2      1225    41.0  40.30  42.30  41.300      0.007264
3      1250    28.5  29.60  31.60  30.600      0.068627
4      1275    22.8  21.30  23.30  22.300      0.022422
5      1300    15.8  15.00  16.20  15.600      0.012821
6      1325     9.5  10.00  11.00  10.500      0.095238
7      1350     6.8   6.30   7.30   6.800      0.000000
8      1375     4.1   4.00   4.70   4.350      0.057471
9      1400     2.5   2.50   3.20   2.850      0.122807
10     1425     1.4   1.40   1.85   1.625      0.138462
11     1450     0.9   0.80   1.25   1.025      0.121951
12     1475     0.5   0.35   0.80   0.575      0.130435

In [4]:
put_df

strikes  mkt_px   bid    ask     mid  relative_err
0       800    1.65   1.2   1.65   1.425      0.157895
1       900    4.30   3.4   4.10   3.750      0.146667
2       950    5.40   5.3   6.30   5.800      0.068966
3       995   10.10   8.5   9.50   9.000      0.122222
4      1025   13.00  11.1  12.60  11.850      0.097046
5      1050   13.60  14.0  15.50  14.750      0.077966
6      1060   16.50  15.7  17.20  16.450      0.003040
7      1075   22.50  18.0  19.50  18.750      0.200000
8      1100   26.00  22.7  24.70  23.700      0.097046
9      1150   39.00  35.3  37.30  36.300      0.074380
10     1175   44.00  44.1  46.10  45.100      0.024390
11     1200   53.00  53.9  55.90  54.900      0.034608

### Average Absolute Error

In [5]:
avg_abs_err_call

0.0723631763800775

In [6]:
avg_abs_err_put

0.09201886445097407

### Payoff Matrix

In [7]:
securities_calls = np.array([0, 0, 0, 0, 1200, 1275, 1350, 1425])
securities_puts = np.array([800, 950, 1050, 1200, 0, 0, 0, 0])

states = np.array([650,875,1000,1125,1237.5,1312.5,1387.5,1500])

In [8]:
def payoff(strike: float, stock: float, o_type: str):
    
    if o_type == "Call":
        if strike <= 0:
            return 0
        else:
            return max((stock - strike), 0)
    elif o_type == "Put":
        return max(strike - stock, 0)
    else:
        print("Enter either o_type = 'Call' or 'Put'")

In [9]:
put_lst=[]

for k in range(0,8):
    put_lst.append([payoff(securities_puts[i], 
           states[k], 
           "Put") for i in range(len(securities_puts))])

In [10]:
call_lst=[]

for k in range(0,8):
    call_lst.append([payoff(securities_calls[i], 
           states[k], 
           "Call") for i in range(len(securities_calls))])

In [11]:
np.array(put_lst).T

array([[150.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [300.,  75.,   0.,   0.,   0.,   0.,   0.,   0.],
       [400., 175.,  50.,   0.,   0.,   0.,   0.,   0.],
       [550., 325., 200.,  75.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [12]:
M = np.array(put_lst).T + np.array(call_lst).T

#### Payoff Matrix

In [13]:
M

array([[150. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [300. ,  75. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [400. , 175. ,  50. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [550. , 325. , 200. ,  75. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  37.5, 112.5, 187.5, 300. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 112.5, 225. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  37.5, 150. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  75. ]])

In [14]:
st0_calls = call_df[call_df['strikes'].isin([1200, 1275, 1350, 1425])]['mid'].values
st0_puts = put_df[put_df['strikes'].isin([1200, 1050, 950, 800])]['mid'].values

St0 = np.concatenate([st0_puts, st0_calls])

In [15]:
solution = np.linalg.solve(M, St0)

In [16]:
print(solution)

[0.0095     0.03933333 0.08133333 0.275      0.246      0.18066667
 0.09466667 0.02166667]


### Answers to Question #2

**(1)**

Print the the Payoff matrix and the St0 (security prices) is shown below. 

In [17]:
print("The Pay of Matrix M is \n")
print(M);
print("\n\n\n")
print("The securities prices St0 is \n")
print(St0)

The Pay of Matrix M is 

[[150.    0.    0.    0.    0.    0.    0.    0. ]
 [300.   75.    0.    0.    0.    0.    0.    0. ]
 [400.  175.   50.    0.    0.    0.    0.    0. ]
 [550.  325.  200.   75.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.   37.5 112.5 187.5 300. ]
 [  0.    0.    0.    0.    0.   37.5 112.5 225. ]
 [  0.    0.    0.    0.    0.    0.   37.5 150. ]
 [  0.    0.    0.    0.    0.    0.    0.   75. ]]




The securities prices St0 is 

[ 1.425  5.8   14.75  54.9   53.8   22.3    6.8    1.625]


**(2)**

In [18]:
matrix_rank = np.linalg.matrix_rank(M)

print(f"These securities are non-redundant if their payoff vectors are linearly independent\
i.e. their row rank is 8. The matrix M is non-singular since the determinant of matrix M is non-zero\
The row rank of Matrix M is {matrix_rank}\n")

print("Therefore we can conclude, that the securities are non-redundant.")

These securities are non-redundant if their payoff vectors are linearly independenti.e. their row rank is 8. The matrix M is non-singular since the determinant of matrix M is non-zeroThe row rank of Matrix M is 8

Therefore we can conclude, that the securities are non-redundant.


**(3)**

Since the one-period market model has the same number of states as the number of securities is complete. if and only if the payoff matrix of the market model is nonsingular. As mentioned above this market model has a determinant that is non-zero, we can conclude that this martix M is nonsingular.

**(4)**

In [19]:
print(f"The enteries of the Q vector are {solution}.\n")
print("Since all the enteries of Q (i.e. the state prices) are, we conclude that the\
one period market model is arbitrage-free.")

The enteries of the Q vector are [0.0095     0.03933333 0.08133333 0.275      0.246      0.18066667
 0.09466667 0.02166667].

Since all the enteries of Q (i.e. the state prices) are, we conclude that theone period market model is arbitrage-free.


**(5)**

*TODO*

Is the question asking about the Vmid? and the relative approximation error as shown above. What comments should we have for this question?